/-
Copyright (c) 2026 Elena Caviglia, Luca Mesiti, Tim Van der Linden.
All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Algebra.Ring.PUnit
import SnakeLean.DiExact
import SnakeLean.SerreQuotient

/-!
# The 2-categories of abelian categories: `AbCat` and `Sat`

Section 8 `S:Model`: Theorem 8.17 `T:SatModel`, with Corollary 8.27 `C:Populated`. The paper
works in `AbCat`, the 2-category of abelian categories, exact functors and natural
transformations, shows it is not 2-di-exact (Proposition 8.12 `P:AbCatFails`), and cuts out the
full sub-2-category `Sat` on the *saturated* abelian categories (Definition 8.15 `D:SAT` --- for
all Serre classes `K` and `S`, the `S`-saturation of `K` is again a Serre class), which is
closed under Serre subcategories and Serre quotients (Proposition 8.16 `P:SATclosed`) and is
2-di-exact.

The module is parametrised by a **class** of abelian categories, `AbCatClass`, exactly as
`SnakeLean.LatticeModel` is parametrised by `LatticeClass`: a property of abelian categories
that holds of the zero category and is inherited by Serre subcategories, which are the two
closure conditions the constructions below consume. `AbCatOf C` is the 2-category on the class,
with the exact functors as 1-cells and the natural transformations as 2-cells; `AbCatClass.all`
gives the paper's `AbCat`, and `AbCatClass.sat` gives `Sat`. Everything proved here is proved
for every class, hence in `AbCat` itself: the zero category is a strong bizero object
(Proposition 8.3 `P:AbCatBizero`), and the 2-kernel of an exact functor is the full subcategory
of the objects it annihilates (Proposition 8.4 `P:AbCatKernel`). That is the 2-kernel half of
(DI1) for `Sat`; the 2-cokernel half and (DI2) are not proved, for the reason given below.

## Main results

* `AbCatClass`, `AbCatOf` --- the class and its 2-category; `bicategoryAbCatOf` and
  `strictAbCatOf` make it a strict bicategory, with the composition, whiskering and coherence
  data of `Cat` and only the 1-cells cut down. `AbCat` and `SatCat` are the two instances.
* `ZeroCat`, `zeroAbCatOf`, `hasBizeroAbCatOf`, `isStrong_zeroAbCatOf` --- the zero abelian
  category, built from scratch, is a strong bizero object (`P:AbCatBizero`).
* `subAbCatOf` --- a Serre subcategory of an object is again one; for `AbCatClass.sat` this is
  the first half of `P:SATclosed` read in the 2-category (`condSAT_fullSubcategory`).
* `isTwoKernel_kerIncl` --- **the 2-kernel of an exact functor is the full subcategory of the
  objects it annihilates**, with its universal property (`P:AbCatKernel`). This is the 2-kernel
  half of (DI1), and it is proved.
* `exists_serreClass_of_isNormalMono` --- hence a normal 2-monomorphism is, up to equivalence,
  the inclusion of a Serre subcategory: the 2-monomorphism half of Corollary 8.6 `C:AbCatNormal`,
  and the step the proof of Proposition 8.11 `P:DIabcat` opens with.

## Not formalised, and why

**2-cokernels, and so the second half of (DI1)** --- Proposition 8.5 `P:AbCatCokernel`. The
2-cokernel of an exact functor `F` is the Serre quotient of its target by the Serre class
generated by the image of `F`. Mathlib has the Serre quotient only as a localisation; that it is
abelian is listed there as future work. So the object does not exist to be exhibited, and
hypothesising it would mean hypothesising its universal property, which is the whole of the
statement.

**(DI2)** --- Proposition 8.11 `P:DIabcat`, the reduction to (SAT). Its proof needs, beyond
`condSAT_fullSubcategory` and `condSAT_of_isSerreQuotient` --- both proved, in
`SnakeLean/SerreSubcategory.lean` and `SnakeLean/SerreQuotient.lean` --- four further facts
about the Serre quotient: that the projection is a 2-cokernel (Proposition 8.5), that the
essential image of `K` in `A / S` is the `S`-saturation of `K` (Definition 8.8 `D:Saturation`
with Proposition 8.9 `P:Saturation`), that a fully faithful exact functor whose essential image
is a Serre class is an equivalence onto the corresponding Serre subcategory (Lemma 8.10
`L:FullyFaithful`), and Gabriel's correspondence. Every one of them is about Serre quotients, so
none of them is available; the mathematical content that is *not* about Serre quotients is
exactly condition (SAT), and that is machine-checked. `T:SatModel` is therefore `AbCatClass.sat`
together with these, and is not claimed; nor, for the same reason, are Corollary 8.6, Proposition
8.11 and Proposition 8.12.
-/

universe v u

namespace SnakeLean

open CategoryTheory Bicategory Limits ZeroObject ObjectProperty

/-! ## The zero abelian category -/

/-- The zero abelian category: one object, one morphism. -/
def ZeroCat : Type u := PUnit.{u + 1}

namespace ZeroCat

instance category : Category.{v} ZeroCat.{u} where
  Hom _ _ := PUnit.{v + 1}
  id _ := ⟨⟩
  comp _ _ := ⟨⟩

instance (X Y : ZeroCat.{u}) : Subsingleton (X ⟶ Y) := inferInstanceAs (Subsingleton PUnit)

instance : Preadditive ZeroCat.{u} where
  homGroup _ _ := inferInstanceAs (AddCommGroup PUnit.{v + 1})
  add_comp := by intros; apply Subsingleton.elim
  comp_add := by intros; apply Subsingleton.elim

theorem isZero (X : ZeroCat.{u}) : IsZero X :=
  ⟨fun _ => ⟨⟨⟨⟩⟩, fun _ => Subsingleton.elim _ _⟩,
   fun _ => ⟨⟨⟨⟩⟩, fun _ => Subsingleton.elim _ _⟩⟩

instance : HasZeroObject ZeroCat.{u} := ⟨⟨⟨⟩, isZero _⟩⟩

instance {X Y : ZeroCat.{u}} (f : X ⟶ Y) : IsIso f :=
  ⟨⟨⟨⟩, Subsingleton.elim _ _, Subsingleton.elim _ _⟩⟩

instance hasLimitsOfShape (J : Type*) [Category J] : HasLimitsOfShape J ZeroCat.{u} where
  has_limit _ := ⟨⟨⟨⟨⟨⟩, ⟨fun _ => ⟨⟩, by intros; apply Subsingleton.elim⟩⟩,
    ⟨fun _ => ⟨⟩, by intros; apply Subsingleton.elim, by intros; apply Subsingleton.elim⟩⟩⟩⟩

instance hasColimitsOfShape (J : Type*) [Category J] : HasColimitsOfShape J ZeroCat.{u} where
  has_colimit _ := ⟨⟨⟨⟨⟨⟩, ⟨fun _ => ⟨⟩, by intros; apply Subsingleton.elim⟩⟩,
    ⟨fun _ => ⟨⟩, by intros; apply Subsingleton.elim, by intros; apply Subsingleton.elim⟩⟩⟩⟩

instance : HasFiniteProducts ZeroCat.{u} := ⟨fun _ => inferInstance⟩

noncomputable instance : Abelian ZeroCat.{u} := Abelian.ofCoimageImageComparisonIsIso

/-- The zero category satisfies (SAT), every saturation being everything. -/
theorem condSAT : CondSAT ZeroCat.{u} := by
  intro S K _ _
  have h : serreSaturation S K = ⊤ :=
    le_antisymm le_top (fun X _ => le_serreSaturation S K X (K.prop_of_isZero (isZero X)))
  rw [h]
  infer_instance

end ZeroCat

/-! ## Classes of abelian categories, and the 2-category on a class -/

/-- **A class of abelian categories**, closed under the two constructions the 2-category makes:
it contains the zero category and is closed under Serre subcategories. `AbCatClass.all` is the
paper's `AbCat`, `AbCatClass.sat` its `Sat`.

The universe parameters are intended to be given explicitly, as for `CategoryTheory.Cat`. -/
@[nolint checkUnivs]
structure AbCatClass.{v', u'} where
  /-- The class, as a property of abelian categories. -/
  Mem : (A : Type u') → [Category.{v'} A] → [Abelian A] → Prop
  /-- It contains the zero category. -/
  mem_zeroCat : Mem ZeroCat.{u'}
  /-- It is closed under Serre subcategories. -/
  mem_fullSubcategory : ∀ {A : Type u'} [Category.{v'} A] [Abelian A]
    (S : ObjectProperty A) [S.IsSerreClass], Mem A → Mem S.FullSubcategory

/-- The class of all abelian categories. -/
def AbCatClass.all : AbCatClass.{v, u} where
  Mem := fun _ => True
  mem_zeroCat := trivial
  mem_fullSubcategory := fun _ _ _ => trivial

/-- The class of abelian categories satisfying (SAT), Definition 8.15 `D:SAT`. Its closure under
Serre subcategories is the first half of Proposition 8.16 `P:SATclosed`,
`condSAT_fullSubcategory`. -/
def AbCatClass.sat : AbCatClass.{v, u} where
  Mem := fun A => CondSAT A
  mem_zeroCat := ZeroCat.condSAT
  mem_fullSubcategory := fun S _ h => condSAT_fullSubcategory S h

/-- An object of the 2-category on a class: an abelian category in the class.

The universe parameters are intended to be given explicitly, as for `CategoryTheory.Cat`. -/
@[nolint checkUnivs]
structure AbCatOf (C : AbCatClass.{v, u}) where
  /-- The underlying type. -/
  carrier : Type u
  [category : Category.{v} carrier]
  [abelian : Abelian carrier]
  /-- The carrier belongs to the class. -/
  mem : C.Mem carrier

attribute [instance] AbCatOf.category AbCatOf.abelian

/-- **The 2-category `AbCat`** of Section 8 `S:Model`: abelian categories, exact functors and
natural transformations. -/
@[nolint checkUnivs]
abbrev AbCat := AbCatOf AbCatClass.all.{v, u}

/-- **The 2-category `Sat`** of Theorem 8.17 `T:SatModel`: the abelian categories satisfying
(SAT), exact functors and natural transformations. -/
@[nolint checkUnivs]
abbrev SatCat := AbCatOf AbCatClass.sat.{v, u}

variable {C : AbCatClass.{v, u}}

/-- A 1-cell of the 2-category: an exact functor. -/
structure AbCatHom (A B : AbCatOf C) where
  /-- The underlying functor. -/
  functor : A.carrier ⥤ B.carrier
  [additive : functor.Additive]
  [preservesFiniteLimits : PreservesFiniteLimits functor]
  [preservesFiniteColimits : PreservesFiniteColimits functor]

attribute [instance] AbCatHom.additive AbCatHom.preservesFiniteLimits
  AbCatHom.preservesFiniteColimits

namespace AbCatHom

/-- 2-cells are natural transformations of the underlying functors. -/
instance category (A B : AbCatOf C) : Category.{max u v} (AbCatHom A B) where
  Hom F G := F.functor ⟶ G.functor
  id F := 𝟙 F.functor
  comp α β := α ≫ β

@[simp]
lemma id_app {A B : AbCatOf C} (F : AbCatHom A B) (X : A.carrier) :
    NatTrans.app (𝟙 F) X = 𝟙 (F.functor.obj X) := rfl

@[simp]
lemma comp_app {A B : AbCatOf C} {F G H : AbCatHom A B} (α : F ⟶ G) (β : G ⟶ H)
    (X : A.carrier) : NatTrans.app (α ≫ β) X = NatTrans.app α X ≫ NatTrans.app β X := rfl

@[ext]
lemma hom_ext {A B : AbCatOf C} {F G : AbCatHom A B} {α β : F ⟶ G}
    (h : ∀ X, (α : F.functor ⟶ G.functor).app X = (β : F.functor ⟶ G.functor).app X) :
    α = β :=
  NatTrans.ext (funext h)

end AbCatHom

/-- **The 2-category of abelian categories in a class.** Composition, whiskering and the
coherence data are those of `Cat`; only the 1-cells are cut down, to the exact functors. -/
instance bicategoryAbCatOf : Bicategory.{max u v, max u v} (AbCatOf C) where
  Hom A B := AbCatHom A B
  id A := { functor := 𝟭 A.carrier }
  comp F G :=
    { functor := F.functor ⋙ G.functor
      preservesFiniteLimits := comp_preservesFiniteLimits _ _
      preservesFiniteColimits := comp_preservesFiniteColimits _ _ }
  homCategory := AbCatHom.category
  whiskerLeft F _ _ η := Functor.whiskerLeft F.functor η
  whiskerRight η H := Functor.whiskerRight η H.functor
  associator _ _ _ := Iso.refl _
  leftUnitor _ := Iso.refl _
  rightUnitor _ := Iso.refl _
  whiskerLeft_id := by intros; refine NatTrans.ext ?_; funext X; simp
  whiskerLeft_comp := by intros; refine NatTrans.ext ?_; funext X; simp
  id_whiskerLeft := by intros; refine NatTrans.ext ?_; funext X; simp
  comp_whiskerLeft := by intros; refine NatTrans.ext ?_; funext X; simp
  id_whiskerRight := by intros; refine NatTrans.ext ?_; funext X; simp
  comp_whiskerRight := by intros; refine NatTrans.ext ?_; funext X; simp
  whiskerRight_id := by intros; refine NatTrans.ext ?_; funext X; simp
  whiskerRight_comp := by intros; refine NatTrans.ext ?_; funext X; simp
  whisker_assoc := by intros; refine NatTrans.ext ?_; funext X; simp
  whisker_exchange := by intros; refine NatTrans.ext ?_; funext X; simp
  pentagon := by intros; refine NatTrans.ext ?_; funext X; simp
  triangle := by intros; refine NatTrans.ext ?_; funext X; simp

/-- The 2-category is strict, as `Cat` is. -/
instance strictAbCatOf : Bicategory.Strict (AbCatOf C) where
  id_comp _ := rfl
  comp_id _ := rfl
  assoc := by intros; rfl


/-! ## The strong bizero object -/

section Bizero

/-- An additive functor carries a zero object to a zero object. -/
theorem isZero_map_obj {C D : Type*} [Category* C] [Category* D] [HasZeroMorphisms C]
    [HasZeroMorphisms D] (F : C ⥤ D) [F.PreservesZeroMorphisms] {Z : C} (h : IsZero Z) :
    IsZero (F.obj Z) := by
  rw [IsZero.iff_id_eq_zero] at h ⊢
  rw [← F.map_id, h, F.map_zero]

instance additive_toZeroCat {A : Type u} [Category.{v} A] [Preadditive A]
    (G : A ⥤ ZeroCat.{u}) : G.Additive where
  map_add := by intros; apply Subsingleton.elim

instance preservesLimitsOfShape_toZeroCat {A : Type u} [Category.{v} A] (G : A ⥤ ZeroCat.{u})
    (J : Type*) [Category* J] (K : J ⥤ A) : PreservesLimit K G where
  preserves _ := ⟨⟨fun _ => ⟨⟩, by intros; apply Subsingleton.elim,
    by intros; apply Subsingleton.elim⟩⟩

instance preservesColimitsOfShape_toZeroCat {A : Type u} [Category.{v} A] (G : A ⥤ ZeroCat.{u})
    (J : Type*) [Category* J] (K : J ⥤ A) : PreservesColimit K G where
  preserves _ := ⟨⟨fun _ => ⟨⟩, by intros; apply Subsingleton.elim,
    by intros; apply Subsingleton.elim⟩⟩

instance {A : Type u} [Category.{v} A] (G : A ⥤ ZeroCat.{u}) (J : Type*) [Category* J] :
    PreservesLimitsOfShape J G where

instance {A : Type u} [Category.{v} A] (G : A ⥤ ZeroCat.{u}) (J : Type*) [Category* J] :
    PreservesColimitsOfShape J G where

instance {A : Type u} [Category.{v} A] (G : A ⥤ ZeroCat.{u}) : PreservesFiniteLimits G :=
  ⟨fun _ _ _ => inferInstance⟩

instance {A : Type u} [Category.{v} A] (G : A ⥤ ZeroCat.{u}) : PreservesFiniteColimits G :=
  ⟨fun _ _ _ => inferInstance⟩

/-- The unique-up-to-isomorphism functor into the zero category. -/
def toZeroFunctor (A : Type u) [Category.{v} A] : A ⥤ ZeroCat.{u} where
  obj _ := ⟨⟩
  map _ := ⟨⟩

/-- The zero functor out of the zero category. -/
noncomputable def fromZeroFunctor (D : Type u) [Category.{v} D] [HasZeroMorphisms D]
    [HasZeroObject D] : ZeroCat.{u} ⥤ D where
  obj _ := 0
  map _ := 0
  map_id _ := ((isZero_zero D).eq_of_src _ _).symm
  map_comp _ _ := ((isZero_zero D).eq_of_src _ _).symm

section FromZero

variable (D : Type u) [Category.{v} D] [Preadditive D] [HasZeroObject D]

instance : (fromZeroFunctor D).Additive where
  map_add := (isZero_zero D).eq_of_src _ _

instance (J : Type*) [Category* J] (K : J ⥤ ZeroCat.{u}) :
    PreservesLimit K (fromZeroFunctor D) where
  preserves _ := ⟨⟨fun _ => 0, fun _ _ => (isZero_zero D).eq_of_tgt _ _,
    fun _ _ _ => (isZero_zero D).eq_of_tgt _ _⟩⟩

instance (J : Type*) [Category* J] (K : J ⥤ ZeroCat.{u}) :
    PreservesColimit K (fromZeroFunctor D) where
  preserves _ := ⟨⟨fun _ => 0, fun _ _ => (isZero_zero D).eq_of_src _ _,
    fun _ _ _ => (isZero_zero D).eq_of_src _ _⟩⟩

instance (J : Type*) [Category* J] : PreservesLimitsOfShape J (fromZeroFunctor D) where

instance (J : Type*) [Category* J] : PreservesColimitsOfShape J (fromZeroFunctor D) where

instance : PreservesFiniteLimits (fromZeroFunctor D) := ⟨fun _ _ _ => inferInstance⟩

instance : PreservesFiniteColimits (fromZeroFunctor D) := ⟨fun _ _ _ => inferInstance⟩

end FromZero

/-- The zero category, as an object of the 2-category on any class. -/
noncomputable abbrev zeroAbCatOf (C : AbCatClass.{v, u}) : AbCatOf C :=
  { carrier := ZeroCat.{u}, mem := C.mem_zeroCat }

/-- **Proposition 8.3 `P:AbCatBizero`, first half**: the zero category is a bizero object, for
every class and so in `AbCat`. -/
noncomputable instance hasBizeroAbCatOf : HasBizero (zeroAbCatOf C) where
  toZero A := { functor := toZeroFunctor A.carrier }
  fromZero B := { functor := fromZeroFunctor B.carrier }

/-- A null 1-cell annihilates every object: it factors through the zero category, and an exact
functor out of the zero category lands in the zero objects. -/
theorem isZero_obj_of_isNull {A B : AbCatOf C} {m : AbCatHom A B}
    (h : IsNull (zeroAbCatOf C) m) (X : A.carrier) : IsZero (m.functor.obj X) := by
  obtain ⟨t, i, rfl⟩ := h
  haveI : i.functor.Additive := i.additive
  exact isZero_map_obj i.functor (ZeroCat.isZero _)

/-- **Proposition 8.3 `P:AbCatBizero`, second half: the zero category is a strong bizero
object.** Two parallel null 1-cells take every object to a zero object, so there is exactly one
natural transformation between them. -/
instance isStrong_zeroAbCatOf : IsStrong (zeroAbCatOf C) where
  nonempty_hom hm _ :=
    ⟨{ app := fun _ => 0
       naturality := fun _ _ _ => (isZero_obj_of_isNull hm _).eq_of_src _ _ }⟩
  subsingleton_hom hm _ :=
    ⟨fun _ _ => NatTrans.ext (funext fun X => (isZero_obj_of_isNull hm X).eq_of_src _ _)⟩

end Bizero


/-! ## 2-kernels -/

section TwoKernel

/-- An isomorphism of the underlying functors is an isomorphism of 1-cells: the 2-cells of the
2-category *are* the natural transformations. -/
def AbCatHom.isoOfNatIso {A B : AbCatOf C} {F G : AbCatHom A B}
    (e : F.functor ≅ G.functor) : F ≅ G where
  hom := e.hom
  inv := e.inv
  hom_inv_id := e.hom_inv_id
  inv_hom_id := e.inv_hom_id

/-- ... and conversely. -/
def AbCatHom.natIsoOfIso {A B : AbCatOf C} {F G : AbCatHom A B} (e : F ≅ G) :
    F.functor ≅ G.functor where
  hom := e.hom
  inv := e.inv
  hom_inv_id := e.hom_inv_id
  inv_hom_id := e.inv_hom_id

/-- A 1-cell isomorphic to a null one annihilates every object. -/
theorem isZero_obj_of_isEssNull {X Y : AbCatOf C} {m : AbCatHom X Y}
    (h : IsEssNull (zeroAbCatOf C) m) (Z : X.carrier) : IsZero (m.functor.obj Z) := by
  obtain ⟨n, hn, ⟨e⟩⟩ := h
  exact IsZero.of_iso (isZero_obj_of_isNull hn Z) ((AbCatHom.natIsoOfIso e).app Z)

/-- **A Serre subcategory of an object of the 2-category is again one**, by the closure
condition of the class. For `AbCatClass.sat` that condition is `condSAT_fullSubcategory`, the
first half of Proposition 8.16 `P:SATclosed`, read in the 2-category. -/
noncomputable abbrev subAbCatOf (X : AbCatOf C) (S : ObjectProperty X.carrier)
    [ObjectProperty.IsSerreClass S] : AbCatOf C :=
  { carrier := ObjectProperty.FullSubcategory S
    mem := C.mem_fullSubcategory S X.mem }

/-- The inclusion of a Serre subcategory, as a 1-cell. -/
noncomputable def subIncl (X : AbCatOf C) (S : ObjectProperty X.carrier)
    [ObjectProperty.IsSerreClass S] : subAbCatOf X S ⟶ X :=
  ({ functor := ObjectProperty.ι S } : AbCatHom (subAbCatOf X S) X)

variable {A B : AbCatOf C} (F : A ⟶ B)

/-- **The 2-kernel of an exact functor**: the objects it annihilates. They form a Serre class,
being the preimage of the Serre class of zero objects along an exact functor. -/
def kerProp : ObjectProperty A.carrier :=
  ObjectProperty.inverseImage (IsZero (C := B.carrier)) (AbCatHom.functor F)

instance : ObjectProperty.IsSerreClass (kerProp F) := isSerreClass_inverseImage _ _

/-- The 2-kernel, as an object of the 2-category: it belongs to the class because the class is
closed under Serre subcategories. -/
noncomputable abbrev kerAbCatOf : AbCatOf C := subAbCatOf A (kerProp F)

/-- The 2-kernel 1-cell: the inclusion of the annihilated objects. -/
noncomputable abbrev kerIncl : kerAbCatOf F ⟶ A := subIncl A (kerProp F)

/-- The composite of the 2-kernel inclusion with the functor is null. -/
theorem isEssNull_kerIncl_comp : IsEssNull (zeroAbCatOf C) (kerIncl F ≫ F) :=
  ⟨_, isNull_zero1 (zeroAbCatOf C) _ _, ⟨AbCatHom.isoOfNatIso (NatIso.ofComponents
    (fun X => IsZero.iso X.property
      (isZero_obj_of_isNull (isNull_zero1 (zeroAbCatOf C) (kerAbCatOf F) B) X))
    (fun {X _} _ => IsZero.eq_of_src X.property _ _))⟩⟩

/-- **The 2-kernel universal property.** A 1-cell annihilated by `F` factors through the
inclusion of the annihilated objects, and does so exactly. -/
theorem exists_fac_kerIncl {Z : AbCatOf C} (z : Z ⟶ A)
    (hz : IsEssNull (zeroAbCatOf C) (z ≫ F)) :
    ∃ u : Z ⟶ kerAbCatOf F, Nonempty (u ≫ kerIncl F ≅ z) :=
  ⟨({ functor := ObjectProperty.lift (kerProp F) (AbCatHom.functor z)
        (fun X => isZero_obj_of_isEssNull hz X) } : AbCatHom Z (kerAbCatOf F)),
    ⟨AbCatHom.isoOfNatIso (Iso.refl _)⟩⟩

/-- Postcomposition with the inclusion is fully faithful on 2-cells, the inclusion being fully
faithful. -/
instance isTwoMono_kerIncl : IsTwoMono (kerIncl F) where
  full W := ⟨fun θ =>
    ⟨((ObjectProperty.fullyFaithfulι (kerProp F)).whiskeringRight W.carrier).preimage θ,
      ((ObjectProperty.fullyFaithfulι (kerProp F)).whiskeringRight W.carrier).map_preimage θ⟩⟩
  faithful W := ⟨fun h =>
    ((ObjectProperty.fullyFaithfulι (kerProp F)).whiskeringRight W.carrier).map_injective h⟩

/-- **Proposition 8.4 `P:AbCatKernel`: the 2-kernel of an exact functor is the full subcategory
of the objects it annihilates.** Stated for every class, hence in `AbCat`; for `Sat` it is the
2-kernel half of condition (DI1), and it is proved, not hypothesised. -/
theorem isTwoKernel_kerIncl : IsTwoKernel (zeroAbCatOf C) F (kerIncl F) where
  isEssNull_comp := isEssNull_kerIncl_comp F
  fac := exists_fac_kerIncl F
  isTwoMono := isTwoMono_kerIncl F

/-- **A normal 2-monomorphism is the inclusion of a Serre subcategory, up to equivalence.**
This is the step the paper's verification of (DI2) opens with, and with
`isTwoKernel_kerIncl` and the uniqueness of 2-kernels it is immediate. -/
theorem exists_serreClass_of_isNormalMono {K X : AbCatOf C} {m : K ⟶ X}
    (hm : IsNormalMono (zeroAbCatOf C) m) :
    ∃ (S : ObjectProperty X.carrier) (_ : ObjectProperty.IsSerreClass S),
      Nonempty (subAbCatOf X S ≌ K) := by
  obtain ⟨Y, g, hg⟩ := hm
  exact ⟨kerProp g, inferInstance, ⟨hg.equivalence (isTwoKernel_kerIncl g)⟩⟩

end TwoKernel

end SnakeLean
